apiVersion: v1
kind: ConfigMap
metadata:                                                                                                                                        
  name: contexts-cm
data:
  context-name-1: |
    git:
      provider: github
      apiUrl: https://api.github.com/api/v4
      authSecret: secret-name-1

  context-name-2: |
    dockerRegistry:
      provider: dockerhub
      apiUrl: https://api.github.com/api/v4
      authSecret: secret-name-2
